from docx import Document

# Create a new Word document
doc = Document()

# Add header similar to template
doc.add_paragraph("Федеральное государственное бюджетное образовательное учреждение высшего образования")
doc.add_paragraph("«Саратовский государственный технический университет имени Гагарина Ю.А.»")
doc.add_paragraph("Кафедра «____________________»")
doc.add_paragraph("")
doc.add_paragraph("Лабораторная работа 2")
doc.add_paragraph("по курсу «Нечеткие системы»")
doc.add_paragraph("")
doc.add_paragraph("Выполнил:")
doc.add_paragraph("Студент группы ______________ Ф.И.О. ______________")
doc.add_paragraph("")
doc.add_paragraph("«__» ____________ 2025 г.")
doc.add_paragraph("")
doc.add_paragraph("Тема: Нечеткие множества")
doc.add_paragraph("")

# Task 1: Exercises from pages 23-24
doc.add_paragraph("Задание 1. Исследование заданных нечётких множеств")
doc.add_paragraph("По заданным ниже нечётким множествам определить: высоту, нормальность, унимодальность, носитель, ядро, границы, точки перехода, α-уровень при α = 0,4, ближайшее чёткое множество (µ > 0,5).")
doc.add_paragraph("")

# Define examples for five fuzzy sets
# a) Треугольная функция принадлежности A
doc.add_paragraph("1) Нечёткое множество A на универсуме X = [0, 10] с треугольной функцией принадлежности:")
doc.add_paragraph("   μ_A(x) = {")
doc.add_paragraph("       0, x ≤ 2;")
doc.add_paragraph("       (x − 2)/(5 − 2), 2 < x ≤ 5;")
doc.add_paragraph("       (8 − x)/(8 − 5), 5 < x < 8;")
doc.add_paragraph("       0, x ≥ 8.")
doc.add_paragraph("   }")
doc.add_paragraph("   Исследовать:")

# Characteristics for A (fill manually in doc)
doc.add_paragraph("   Высота: 1 (в точке x = 5).")
doc.add_paragraph("   Нормальность: нормальное (есть точка с μ = 1).")
doc.add_paragraph("   Унимодальность: да (одно пиковое значение μ = 1).")
doc.add_paragraph("   Носитель: [2, 8].")
doc.add_paragraph("   Ядро: {5}.")
doc.add_paragraph("   Границы: {x | 0 < μ_A(x) < 1} = (2, 5) ∪ (5, 8).")
doc.add_paragraph("   Точки перехода: решить μ_A(x) = 0,5 → x = 3.5, x = 6.5.")
doc.add_paragraph("   α-уровень при α = 0,4: {x | μ_A(x) ≥ 0,4} = [2 + 0,4·3, 8 − 0,4·3] = [3.2, 6.8].")
doc.add_paragraph("   Ближайшее чёткое множество (μ > 0,5): {x | μ_A(x) > 0,5} = (3.5, 6.5).")
doc.add_paragraph("")

# b) Трапециевидная функция принадлежности B
doc.add_paragraph("2) Нечёткое множество B на универсуме X = [0, 10] с трапециевидной функцией принадлежности:")
doc.add_paragraph("   μ_B(x) = {")
doc.add_paragraph("       0, x ≤ 1;")
doc.add_paragraph("       (x − 1)/(3 − 1), 1 < x ≤ 3;")
doc.add_paragraph("       1, 3 < x ≤ 6;")
doc.add_paragraph("       (8 − x)/(8 − 6), 6 < x < 8;")
doc.add_paragraph("       0, x ≥ 8.")
doc.add_paragraph("   }")
doc.add_paragraph("   Исследовать:")
doc.add_paragraph("   Высота: 1 (на отрезе [3, 6]).")
doc.add_paragraph("   Нормальность: нормальное (есть отрезок с μ = 1).")
doc.add_paragraph("   Унимодальность: да (одно плато с μ = 1).")
doc.add_paragraph("   Носитель: [1, 8].")
doc.add_paragraph("   Ядро: [3, 6].")
doc.add_paragraph("   Границы: (1, 3) ∪ (6, 8).")
doc.add_paragraph("   Точки перехода: μ_B(x) = 0,5 → x = 2, x = 7.")
doc.add_paragraph("   α-уровень при α = 0,4: {x | μ_B(x) ≥ 0,4} = [1 + 0,4·2, 8 − 0,4·2] = [1.8, 7.2].")
doc.add_paragraph("   Ближайшее чёткое множество (μ > 0,5): {x | μ_B(x) > 0,5} = (2, 7).")
doc.add_paragraph("")

# c) Z-образная функция принадлежности C
doc.add_paragraph("3) Нечёткое множество C на универсуме X = [0, 10] с Z-образной функцией принадлежности:")
doc.add_paragraph("   μ_C(x) = {")
doc.add_paragraph("       1, x ≤ 4;")
doc.add_paragraph("       (6 − x)/(6 − 4), 4 < x < 6;")
doc.add_paragraph("       0, x ≥ 6.")
doc.add_paragraph("   }")
doc.add_paragraph("   Исследовать:")
doc.add_paragraph("   Высота: 1 (на отрезе [0, 4]).")
doc.add_paragraph("   Нормальность: нормальное (максимальное значение μ = 1 достигается на интервале).")
doc.add_paragraph("   Унимодальность: да (постоянный максимум).")
doc.add_paragraph("   Носитель: [0, 6].")
doc.add_paragraph("   Ядро: [0, 4].")
doc.add_paragraph("   Границы: (4, 6).")
doc.add_paragraph("   Точка перехода: μ_C(x) = 0,5 → x = 5.")
doc.add_paragraph("   α-уровень при α = 0,4: {x | μ_C(x) ≥ 0,4} = [0, 4] ∪ [4 + 0,6·(1 − 0,4), 6] = [0, 4] ∪ [4.4, 6].")
doc.add_paragraph("   Ближайшее чёткое множество (μ > 0,5): {x | μ_C(x) > 0,5} = [0, 5).")
doc.add_paragraph("")

# d) S-образная функция принадлежности D
doc.add_paragraph("4) Нечёткое множество D на универсуме X = [0, 10] с S-образной функцией принадлежности:")
doc.add_paragraph("   μ_D(x) = {")
doc.add_paragraph("       0, x ≤ 2;")
doc.add_paragraph("       (x − 2)/(5 − 2), 2 < x < 5;")
doc.add_paragraph("       1, x ≥ 5.")
doc.add_paragraph("   }")
doc.add_paragraph("   Исследовать:")
doc.add_paragraph("   Высота: 1 (на отрезе [5, 10]).")
doc.add_paragraph("   Нормальность: нормальное (есть отрез с μ = 1).")
doc.add_paragraph("   Унимодальность: да.")
doc.add_paragraph("   Носитель: [2, 10].")
doc.add_paragraph("   Ядро: [5, 10].")
doc.add_paragraph("   Границы: (2, 5).")
doc.add_paragraph("   Точка перехода: μ_D(x) = 0,5 → x = 3.5.")
doc.add_paragraph("   α-уровень при α = 0,4: {x | μ_D(x) ≥ 0,4} = [2 + 0,4·3, 10] = [3.2, 10].")
doc.add_paragraph("   Ближайшее чёткое множество (μ > 0,5): {x | μ_D(x) > 0,5} = [3.5, 10].")
doc.add_paragraph("")

# e) Дискретное нечёткое множество E
doc.add_paragraph("5) Дискретное нечёткое множество E на универсуме X = {1, 2, 3, 4, 5}:")
doc.add_paragraph("   E = {<1; 0,2>, <2; 0,6>, <3; 1,0>, <4; 0,6>, <5; 0,2>}.")
doc.add_paragraph("   Исследовать:")
doc.add_paragraph("   Высота: 1 (при x = 3).")
doc.add_paragraph("   Нормальность: нормальное.")
doc.add_paragraph("   Унимодальность: да.")
doc.add_paragraph("   Носитель: {1, 2, 3, 4, 5}.")
doc.add_paragraph("   Ядро: {3}.")
doc.add_paragraph("   Границы: {2, 4}.")
doc.add_paragraph("   Точка перехода: μ_E(x) = 0,5 → x не достигается (значения 0,6 и 0,2).")
doc.add_paragraph("   α-уровень при α = 0,4: {x | μ_E(x) ≥ 0,4} = {2, 3, 4}.")
doc.add_paragraph("   Ближайшее чёткое множество (μ > 0,5): {x | μ_E(x) > 0,5} = {2, 3, 4}.")
doc.add_paragraph("")

# Task 2: Exercises from pages 27-28
doc.add_paragraph("Задание 2. Построение нечётких множеств для лингвистических понятий")
doc.add_paragraph("По заданным описаниям построить и описать функции принадлежности следующих нечётких множеств:")
doc.add_paragraph("")

# a) Нечёткое множество «приблизительно равно» числу 50 на X = [0, 100]
doc.add_paragraph("1) «Приблизительно равно 50»:")
doc.add_paragraph("   Предложена гауссиановская функция принадлежности:")
doc.add_paragraph("   μ_A(x) = exp(−((x − 50)²)/(2·10²)).")
doc.add_paragraph("   Высота: 1 (x = 50).")
doc.add_paragraph("   Носитель: теоретически [0, 100], практически где μ(x) > 0 (числовая ось).")
doc.add_paragraph("   Ядро: {50}.")
doc.add_paragraph("   Параметр σ = 10 отвечает степени «приближения».")
doc.add_paragraph("")

# b) Нечёткое множество «среднее значение» температуры (X = [−30, 50] °C)
doc.add_paragraph("2) «Среднее значение температуры»:")
doc.add_paragraph("   Треугольная функция принадлежности:")
doc.add_paragraph("   μ_B(x) = {")
doc.add_paragraph("       0, x ≤ 10;")
doc.add_paragraph("       (x − 10)/(20 − 10), 10 < x ≤ 20;")
doc.add_paragraph("       (30 − x)/(30 − 20), 20 < x < 30;")
doc.add_paragraph("       0, x ≥ 30.")
doc.add_paragraph("   }")
doc.add_paragraph("   Высота: 1 (x = 20).")
doc.add_paragraph("   Носитель: [10, 30].")
doc.add_paragraph("   Ядро: {20}.")
doc.add_paragraph("   Параметры a = 20, α = β = 10.")
doc.add_paragraph("")

# c) Нечёткое множество «температура находится в интервале [0, 100] °C»
doc.add_paragraph("3) «Температура в интервале [0, 100] °C»:")
doc.add_paragraph("   Трапециевидная функция принадлежности:")
doc.add_paragraph("   μ_C(x) = {")
doc.add_paragraph("       0, x ≤ 0;")
doc.add_paragraph("       (x − 0)/(20 − 0), 0 < x ≤ 20;")
doc.add_paragraph("       1, 20 < x ≤ 80;")
doc.add_paragraph("       (100 − x)/(100 − 80), 80 < x < 100;")
doc.add_paragraph("       0, x ≥ 100.")
doc.add_paragraph("   }")
doc.add_paragraph("   Высота: 1.")
doc.add_paragraph("   Носитель: [0, 100].")
doc.add_paragraph("   Ядро: [20, 80].")
doc.add_paragraph("")

# d) Нечёткое множество «значения похожи на эталон 75» (X = [0, 150])
doc.add_paragraph("4) «Похожи на эталон 75»:")
doc.add_paragraph("   S-образная функция принадлежности для ближнего к 75:")
doc.add_paragraph("   μ_D(x) = {")
doc.add_paragraph("       0, x ≤ 50;")
doc.add_paragraph("       (x − 50)/(75 − 50), 50 < x < 75;")
doc.add_paragraph("       1, x ≥ 75.")
doc.add_paragraph("   }")
doc.add_paragraph("   Высота: 1 (x ≥ 75).")
doc.add_paragraph("   Носитель: [50, 150].")
doc.add_paragraph("   Ядро: [75, 150].")
doc.add_paragraph("")

# e) Нечёткое множество «значения подобны эталону 25» (X = [0, 50])
doc.add_paragraph("5) «Подобны эталону 25»:")
doc.add_paragraph("   Z-образная функция принадлежности:")
doc.add_paragraph("   μ_E(x) = {")
doc.add_paragraph("       1, x ≤ 25;")
doc.add_paragraph("       (35 − x)/(35 − 25), 25 < x < 35;")
doc.add_paragraph("       0, x ≥ 35.")
doc.add_paragraph("   }")
doc.add_paragraph("   Высота: 1 (x ≤ 25).")
doc.add_paragraph("   Носитель: [0, 35].")
doc.add_paragraph("   Ядро: [0, 25].")
doc.add_paragraph("")

# Save the document
output_path = "./idk.docx"
doc.save(output_path)

# Provide the download link
output_path